version: 1
env:
  variables:
    GO_VERSION: 1.24.3
    HUGO_VERSION: 0.147.6
    # Time zone
    TZ: Europe/London
    HUGO_CACHEDIR: ${PWD}/.hugo
frontend:
   phases:
      preBuild:
         commands:
            # Install Go
            - curl -LJO https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
            - sudo tar -C /usr/local -xf go${GO_VERSION}.linux-amd64.tar.gz
            - rm go${GO_VERSION}.linux-amd64.tar.gz
            - export PATH=/usr/local/go/bin:$PATH

            # Install Hugo
            - curl -LJO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
            - sudo tar -C /usr/local/bin -xf hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
            - rm hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
            - export PATH=/usr/local/bin:$PATH

            # Check installed versions
            - go version
            - hugo version
            
            - cd rnp
      build:
         commands:
            - hugo --gc --minify
   artifacts:
      baseDirectory: rnp/public
      files:
         - '**/*'
   cache:
      paths: 
         - ${HUGO_CACHEDIR}/**/*
