config:
  github:token:
    secure: AAABAIh71TYpBO5pUetTn/frCQ9xPq3O66uemOueovGTr6zB6BzOjk8RcMFP1F+X2EIjhGwAt3qbtUC7qCnvrgY6gWsmWspV0p8Pn0a12VW70hU/ym/lWujKg0eO9zzeGMjIjtBFoDufZ8OB3OC2t87KRykHfWUbnH/rKvg=
  statuscake:apiToken:
    secure: AAABAKGQ8fBiLdI0wUjTyvhbcSljbehjHF+Hjo4FoDFlGcs2MFLe+FsO8tmN52h9kvkufZmKVrnJysIFH78=
  cloudflare:apiToken:
    secure: AAABAFIPTNUTJuCIC4fPEV4d2DxorhyTA0GTNCVyMLuiOV+/lNsBsy5LRvB13BSgW+02M+1jEvJSqMvIFu621d/hGbcJyBNZ
  rnp:account_id:
    secure: AAABAGaLny+VcyoWs4pdzyGB2cAd1EVh6trg0Xaty77oHtj8wv0BUTuHcypvIh1Ao4T+s8nZVjqsAEy773Rmcg==
  rnp:zone_id:
    secure: AAABABV/sVKPao9Fy5CrfNqnLsDCJXLs2gE0gn7kCbLK10GKgqhlOQzAKdYwhdtwqA1M9lBprbMSD/kBonivpA==
