theme = 'ananke'
title = 'Rum and Popcorn'
baseURL = 'https://www.rumandpopcorn.com'
disablePathToLower = true
languageCode = 'en-gb'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    post = "/:year/:month/:slug"

[params]
  date_format = "02 Jan 2006"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"