name: Jekyll Build & Deploy
on:
  push:
    branches: 
      - 'main'
      - 'action-test'
      - 'staging'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build
        uses: vivi90/jekyll-minimal-action@v1.1.0
        with:
          command: jekyll build
      - name: Post-Build
        run: |
          ls -lR ./_site
