name: Jekyll Build & Deploy
on:
  push:
    branches: ['main', 'action-test']
jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build
        uses: lemonarc/jekyll-action@1.0.0
      - name: Post-Build
        run: |
          ls -lR ./_site
